# Generated by Django 3.2.3 on 2022-05-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('idFormato', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombreFormato', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('idLab', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombreLab', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo', models.IntegerField(max_length=99999999, primary_key=True, serialize=False)),
                ('nombreMed', models.CharField(max_length=25)),
                ('principio', models.CharField(max_length=25)),
                ('stock', models.IntegerField(max_length=9999)),
                ('vencimiento', models.DateField()),
                ('reservado', models.IntegerField(max_length=999)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.formato')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('rutPaciente', models.CharField(max_length=10)),
                ('telefonoPac', models.IntegerField(max_length=10)),
                ('correoPac', models.CharField(max_length=60)),
                ('observacion', models.CharField(max_length=200)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=12)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='rutMed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.usuario'),
        ),
    ]
