# Generated by Django 3.2.9 on 2022-05-17 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Categoría (uso interno)')),
                ('nombreCat', models.CharField(max_length=40, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('idFormato', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Formato (uso interno)')),
                ('nombreFormato', models.CharField(max_length=25, verbose_name='Formato del Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('idLab', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del laboratorio (uso interno)')),
                ('nombreLab', models.CharField(max_length=25, verbose_name='Nombre del Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rutPaciente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Paciente')),
                ('nombresPac', models.CharField(max_length=40, verbose_name='Nombres del Paciente')),
                ('apellidosPac', models.CharField(max_length=40, verbose_name='Apellidos del Paciente')),
                ('telefonoPac', models.IntegerField(verbose_name='Celular del Paciente')),
                ('correoPac', models.CharField(max_length=60, verbose_name='Correo electrónico del Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Receta (uso interno)')),
                ('fechaReceta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('observacion', models.CharField(max_length=200, verbose_name='Observación del Médico')),
                ('rutReceptor', models.CharField(default=0, editable=False, max_length=10, verbose_name='Rut del que Retira')),
                ('entregada', models.BooleanField(verbose_name='Receta Entregada')),
                ('rutMed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('rutPaciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del Medicamento')),
                ('nombreMed', models.CharField(max_length=25, verbose_name='Nombre del Medicamento')),
                ('principio', models.CharField(max_length=40, verbose_name='Principio Activo')),
                ('stock', models.IntegerField(verbose_name='Stock del Medicamento')),
                ('vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('reservado', models.IntegerField(default=0, verbose_name='Cantidad Reservada')),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='reserva.categoria')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.formato')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del Medicamento')),
                ('codmed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.medicamento')),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.receta')),
            ],
        ),
    ]
