# Generated by Django 3.2.3 on 2022-05-16 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCat', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('idFormato', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFormato', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('idLab', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLab', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMed', models.CharField(max_length=25)),
                ('principio', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('reservado', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='reserva.categoria')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.formato')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rutPaciente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombresPac', models.CharField(max_length=40)),
                ('apellidosPac', models.CharField(max_length=40)),
                ('telefonoPac', models.IntegerField()),
                ('correoPac', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReceta', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=200)),
                ('rutReceptor', models.CharField(default=0, editable=False, max_length=10)),
                ('entregada', models.BooleanField()),
                ('medicamento', models.ManyToManyField(to='reserva.Medicamento')),
                ('rutMed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('rutPaciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.paciente')),
            ],
        ),
    ]
