# Generated by Django 3.2.3 on 2022-05-16 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='medicamento',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción de la Categoría'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Categoría (uso interno)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCat',
            field=models.CharField(max_length=40, verbose_name='Nombre de la Categoría'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='idFormato',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Formato (uso interno)'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='nombreFormato',
            field=models.CharField(max_length=25, verbose_name='Formato del Medicamento'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='idLab',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id del laboratorio (uso interno)'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nombreLab',
            field=models.CharField(max_length=25, verbose_name='Nombre del Laboratorio'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código del Medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombreMed',
            field=models.CharField(max_length=25, verbose_name='Nombre del Medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='principio',
            field=models.CharField(max_length=40, verbose_name='Principio Activo'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='reservado',
            field=models.IntegerField(default=0, verbose_name='Cantidad Reservada'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(verbose_name='Stock del Medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='vencimiento',
            field=models.DateField(verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidosPac',
            field=models.CharField(max_length=40, verbose_name='Apellidos del Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correoPac',
            field=models.CharField(max_length=60, verbose_name='Correo electrónico del Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombresPac',
            field=models.CharField(max_length=40, verbose_name='Nombres del Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rutPaciente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefonoPac',
            field=models.IntegerField(verbose_name='Celular del Paciente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='entregada',
            field=models.BooleanField(verbose_name='Receta Entregada'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fechaReceta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='idReceta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Receta (uso interno)'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='observacion',
            field=models.CharField(max_length=200, verbose_name='Observación del Médico'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='rutReceptor',
            field=models.CharField(default=0, editable=False, max_length=10, verbose_name='Rut del que Retira'),
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('idreceta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='reserva.receta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del Medicamento')),
                ('codmed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserva.medicamento')),
            ],
        ),
    ]
