# Generated by Django 3.2.3 on 2022-05-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20220516_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='correoPac',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefonoPac',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='entregada',
            field=models.BooleanField(default=False, verbose_name='Receta Entregada'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='rutMed',
            field=models.CharField(max_length=50),
        ),
    ]
