# Generated by Django 3.2.3 on 2022-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20220515_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='idFormato',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
