# Generated by Django 3.2.3 on 2022-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20220518_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallereceta',
            name='codmed',
            field=models.IntegerField(),
        ),
    ]
