# Generated by Django 3.2.3 on 2022-05-15 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_formato_idformato'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='fechaReceta',
            field=models.DateField(default=datetime.date(2022, 5, 15)),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='reservado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='vencimiento',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='telefonoPac',
            field=models.IntegerField(),
        ),
    ]
